# Generated by Django 5.0.6 on 2024-07-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_system", "0002_alter_customeruserprofile_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customeruserprofile",
            old_name="confirm_password",
            new_name="password1",
        ),
        migrations.AddField(
            model_name="customeruserprofile",
            name="password2",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customeruserprofile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
