# Generated by Django 5.0.6 on 2024-07-09 09:31

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "login_system",
            "0003_rename_confirm_password_customeruserprofile_password1_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customeruserprofile",
            managers=[
                ("custommanager", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="customeruserprofile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
