# Generated by Django 5.0.6 on 2024-07-09 09:36

import django.contrib.auth.models
import login_system.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_system", "0004_alter_customeruserprofile_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customeruserprofile",
            managers=[
                ("custommanager", login_system.models.CustomUserManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
