# Generated by Django 4.2.14 on 2024-07-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0005_alter_customeruserprofile_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=256)),
                ('summary', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categeory_name', models.CharField(max_length=50)),
                ('category_slug', models.SlugField()),
            ],
        ),
    ]
