# Generated by Django 4.2.14 on 2024-07-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('login_system', '0008_customuserprofile_delete_customeruserprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserProfile',
            new_name='CustomerUserProfile',
        ),
    ]
