# Generated by Django 4.2.14 on 2024-07-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0009_rename_customuserprofile_customeruserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categeory_name',
            new_name='category_name',
        ),
    ]
